version: "3.9"

services:
  app:
    image: faridaamr578/think-search-app:latest   
    container_name: search_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - qdrant

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.10.0
    container_name: qdrant_db
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

volumes:
  mongo_data:
  qdrant_storage:
